os: osx
osx_image: xcode10
language: objective-c
before_script:
  - gem install xcpretty || true
script:
  - xcodebuild -project RMStore.xcodeproj -scheme 'RMStoreExcludeKeychainTests' -configuration Release -sdk iphonesimulator | xcpretty
  - xcodebuild -project RMStore.xcodeproj -scheme 'RMStoreExcludeKeychainTests' -destination 'platform=iOS Simulator,name=iPhone SE,OS=12.0' test | xcpretty
branches:
  only:
    - master
